### ISSUE TITLE
When on "all order page" the back button should go to the menu not the empty order

### ISSUE THREAD

**Issue by RenoMuijsenberg** [S3-Proftaakgroep-3/Mediaan-DMA#115]

**Comment by RenoMuijsenberg** [comment]
Wanneer order is geplaatst ga je naar all orders en op de terug knop willen we liever naar het menu.

**Comment by MikeVerlinde** [comment]
Wanneer je een order succesvol plaatst, redirect hij je naar de homepagina. De orderBackButton doet nog steeds router.back(). Anders zou één button twee verschillende dingen moeten doen, op basis van de pagina die je daarvoor was.
